---
date_and_time:
  short_date_format: "%Y-%m-%d"
  long_date_format: "%a %b %d, %Y %l:%M%P"
  time_format: "%l:%M%p"
  date_entry_format_help: yyyy-mm-dd
  date_and_time_entry_format: "%Y-%m-%d %l:%M%p"
  date_and_time_entry_format_help: yyyy-mm-dd hh:mm<AM or PM>
